name: .NET Core CI/CD

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  setup:
    name: ğŸ”§ Setup .NET Environment
    runs-on: ubuntu-latest
    outputs:
      dotnet-version: 9.0.x # Definir la versiÃ³n de .NET como variable de salida
    steps:
      - name: Checkout Repository ğŸ“‚
        uses: actions/checkout@v4

      - name: Install .NET SDK ğŸ› ï¸
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 9.0.x

  restore:
    name: ğŸ“¦ Restore Dependencies
    runs-on: ubuntu-latest
    needs: setup
    steps:
      - name: Checkout Repository ğŸ“‚
        uses: actions/checkout@v4

      - name: Restore Dependencies ğŸ”„
        run: dotnet restore

  build:
    name: ğŸ—ï¸ Build Project
    runs-on: ubuntu-latest
    needs: restore
    steps:
      - name: Checkout Repository ğŸ“‚
        uses: actions/checkout@v4

      - name: Build Solution ğŸ—ï¸
        run: dotnet build --no-restore

  test:
    name: ğŸ§ª Run Tests
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout Repository ğŸ“‚
        uses: actions/checkout@v4

      - name: Execute Tests ğŸš€
        run: dotnet test --no-build --verbosity normal
